#!/usr/bin/env python3
"""Generate the Macau streetscape OBJ kit without third-party dependencies."""
from __future__ import annotations

import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class Mesh:
    def __init__(self) -> None:
        self.vertices: list[tuple[float, float, float]] = []
        self.faces: list[tuple[str, tuple[int, ...]]] = []

    def box(self, center, size, material="metal"):
        cx, cy, cz = center; sx, sy, sz = (v / 2 for v in size)
        start = len(self.vertices) + 1
        self.vertices += [(cx+x*sx, cy+y*sy, cz+z*sz)
                          for x,y,z in [(-1,-1,-1),(1,-1,-1),(1,1,-1),(-1,1,-1),
                                        (-1,-1,1),(1,-1,1),(1,1,1),(-1,1,1)]]
        for face in [(0,3,2,1),(4,5,6,7),(0,1,5,4),(1,2,6,5),(2,3,7,6),(3,0,4,7)]:
            self.faces.append((material, tuple(start+i for i in face)))
        return self

    def cylinder(self, center, radius, height, material="metal", sides=12):
        cx, cy, cz = center; start = len(self.vertices) + 1
        for z in (-height/2, height/2):
            self.vertices += [(cx+radius*math.cos(2*math.pi*i/sides),
                               cy+radius*math.sin(2*math.pi*i/sides), cz+z)
                              for i in range(sides)]
        self.faces += [(material, tuple(start+i for i in range(sides-1,-1,-1))),
                       (material, tuple(start+sides+i for i in range(sides)))]
        for i in range(sides):
            j=(i+1)%sides
            self.faces.append((material,(start+i,start+j,start+sides+j,start+sides+i)))
        return self

    def write(self, relative):
        path = ROOT / relative; path.parent.mkdir(parents=True, exist_ok=True)
        lines = ["# Generated by tools/generate_assets.py", "mtllib ../materials.mtl", f"o {path.stem}"]
        lines += [f"v {x:.5f} {y:.5f} {z:.5f}" for x,y,z in self.vertices]
        current = None
        for material, face in self.faces:
            if material != current: lines.append(f"usemtl {material}"); current = material
            lines.append("f " + " ".join(map(str, face)))
        path.write_text("\n".join(lines)+"\n")


def pole(mesh, height=4.8, material="painted_black"):
    return mesh.cylinder((0,0,height/2),.055,height,material).cylinder((0,0,.08),.14,.16,material)


def generate_environment():
    Mesh().box((0,0,.075),(2,2,.15),"concrete").write("assets/environment/sidewalk_2m.obj")
    Mesh().box((0,0,.125),(1,.30,.25),"concrete").write("assets/environment/curb_straight_1m.obj")
    # Corner consists of short tangent segments, making it snap-compatible.
    m=Mesh(); m.box((-.35,0,.125),(.70,.30,.25),"concrete"); m.box((0,.35,.125),(.30,.70,.25),"concrete"); m.write("assets/environment/curb_corner_90.obj")
    Mesh().box((0,0,.025),(2,2,.05),"asphalt").write("assets/environment/asphalt_2m.obj")
    m=Mesh().box((0,0,.035),(.55,.32,.07),"metal")
    for x in [-.20,-.10,0,.10,.20]: m.box((x,0,.076),(.025,.25,.012),"dark_concrete")
    m.write("assets/environment/storm_drain.obj")
    Mesh().cylinder((0,0,.025),.34,.05,"metal",20).cylinder((0,0,.055),.24,.012,"dark_concrete",20).write("assets/environment/manhole_cover.obj")
    Mesh().box((0,0,.007),(3,.10,.014),"white").write("assets/environment/road_marking_white_3m.obj")
    Mesh().box((0,0,.007),(3,.10,.014),"yellow").write("assets/environment/road_marking_yellow_3m.obj")
    Mesh().box((0,0,.007),(.45,3.5,.014),"white").write("assets/environment/crosswalk_bar.obj")


def generate_furniture():
    m=pole(Mesh(),5.2); m.box((0,.42,5.12),(.08,.85,.08),"painted_black").box((0,.79,4.98),(.28,.42,.13),"white").write("assets/street_furniture/lamp_post.obj")
    m=pole(Mesh(),3.2,"painted_green"); m.box((0,.08,2.62),(.34,.28,.90),"painted_black")
    for z,mat in [(2.92,"red"),(2.62,"amber"),(2.32,"signal_green")]: m.cylinder((0,.235,z),.095,.035,mat,16)
    m.write("assets/street_furniture/traffic_light.obj")
    pole(Mesh(),2.5,"galvanized").box((0,0,2.15),(.72,.06,.55),"blue").write("assets/street_furniture/road_sign.obj")
    pole(Mesh(),2.35,"painted_black").box((0,0,2.05),(.76,.055,.24),"white").box((0,-.033,2.05),(.70,.008,.16),"blue").write("assets/street_furniture/street_name_sign.obj")
    m=Mesh()
    for x in (-.72,0,.72): m.cylinder((x,0,.52),.035,1.04,"galvanized",10)
    m.box((0,0,.72),(1.5,.045,.045),"galvanized").box((0,0,.32),(1.5,.045,.045),"galvanized").write("assets/street_furniture/pedestrian_railing.obj")
    Mesh().box((0,0,.58),(.62,.35,1.16),"painted_green").box((0,-.181,.72),(.42,.015,.18),"white").write("assets/street_furniture/electrical_box.obj")
    Mesh().cylinder((0,0,.38),.13,.76,"red",12).cylinder((0,0,.78),.18,.10,"red",12).box((0,0,.87),(.22,.22,.08),"red").write("assets/street_furniture/fire_hydrant.obj")
    Mesh().cylinder((0,0,.46),.25,.92,"plastic",14).cylinder((0,0,.92),.27,.08,"painted_green",14).write("assets/street_furniture/litter_bin.obj")
    m=Mesh().box((0,0,1.18),(2.8,.10,2.36),"glass").box((0,.46,2.38),(3.0,1.02,.10),"metal").box((0,.28,.48),(1.55,.38,.10),"metal")
    for x in (-1.4,1.4): m.box((x,0,1.18),(.08,.08,2.36),"metal")
    m.write("assets/street_furniture/bus_shelter.obj")
    pole(Mesh(),2.75,"painted_green").box((0,0,2.30),(.48,.08,.66),"blue").write("assets/street_furniture/bus_stop_flag.obj")
    Mesh().box((0,0,.55),(.30,.24,1.10),"metal").box((0,-.13,.72),(.21,.025,.26),"glass").write("assets/street_furniture/parking_meter.obj")
    Mesh().cylinder((0,0,.38),.075,.76,"painted_black",12).cylinder((0,0,.78),.11,.08,"painted_black",12).write("assets/street_furniture/bollard.obj")


def generate_details():
    Mesh().cylinder((0,0,1.5),.035,3,"galvanized",10).write("assets/urban_details/exposed_pipe.obj")
    Mesh().cylinder((0,0,1.5),.012,3,"painted_black",8).write("assets/urban_details/facade_cable.obj")
    Mesh().cylinder((0,0,.55),.018,1.1,"white",8).box((0,.10,.04),(.04,.24,.04),"white").write("assets/urban_details/ac_drain.obj")
    Mesh().box((0,0,.12),(.24,.42,.24),"painted_black").cylinder((0,.24,.12),.085,.18,"glass",12).box((0,0,-.12),(.06,.06,.24),"metal").write("assets/urban_details/cctv_camera.obj")
    m=Mesh()
    for x in (-.65,.65): m.box((x,0,.55),(.035,.035,1.1),"galvanized")
    for y in (0,.28,.56): m.box((0,y,.92),(1.3,.025,.025),"galvanized")
    m.write("assets/urban_details/drying_rack.obj")
    m=Mesh()
    for x in [-.6,-.3,0,.3,.6]: m.box((x,0,.75),(.025,.025,1.5),"metal")
    for z in [.05,.4,.75,1.1,1.45]: m.box((0,0,z),(1.25,.025,.025),"metal")
    m.write("assets/urban_details/security_grille.obj")
    Mesh().box((0,0,.45),(1.25,.18,.9),"red").box((0,-.10,.45),(1.12,.025,.72),"white").write("assets/urban_details/ad_lightbox.obj")
    Mesh().box((0,0,.42),(.72,.56,.84),"plastic").box((0,-.30,.60),(.58,.03,.22),"glass").write("assets/urban_details/storefront_machine.obj")


def generate_mobility():
    m=Mesh().box((0,0,.48),(1.72,3.75,.62),"white").box((0,-.15,.98),(1.45,1.75,.55),"glass")
    for x in (-.72,.72):
        for y in (-1.18,1.18): m.cylinder((x,y,.28),.25,.18,"painted_black",12)
    m.write("assets/mobility/compact_car.obj")
    m=Mesh().cylinder((0,0,1.55),.13,.26,"plastic",12).box((0,0,1.0),(.38,.24,.78),"blue")
    for x in (-.11,.11): m.box((x,0,.36),(.12,.14,.72),"dark_concrete")
    m.write("assets/mobility/pedestrian.obj")


if __name__ == "__main__":
    generate_environment(); generate_furniture(); generate_details(); generate_mobility()
    print("Generated modular Macau streetscape assets")
